spring:
  config:
    activate:
      on-profile: staging
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://ec2-23-22-191-232.compute-1.amazonaws.com/d5kogcije27pq3
    username: vobcopjcigcjxy
    password: 7979b0b3ef07f0768ad7d472f8c4e1ad0cb09981e49859f034179a019905be17