spring:
  config:
    activate:
      on-profile: prod
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://ec2-23-22-191-232.compute-1.amazonaws.com/d1h0l81pvekv04
    username: ldbntivcyiuhkr
    password: 11652e80afd231e106d6e4357fd5444bedb92b01c8ab966ddd6b06284cfd1edf
